### ISSUE TITLE
$this-> call to self:: call

### ISSUE THREAD

**Issue by Drizzlecrj** [sebastianbergmann/phpunit-documentation#121]
In the documentation, $this call is used everywhere, e.g. $this->assertArrayHasKey, $this->assertEquals, etc.

However, those functions are all static functions.
Though PHP does support that, would it be great to use the 'right way' to call a static function?

I checked some other _Unit, they are using Assert.assert_.

**Comment by KingCrunch** [comment]
Hi @sebastianbergmann 

Do you still think it is irrelevant, or would you accept a PR? It's because I found people seeing this as best practice, although they know it's "wrong". Albeit it technically works I don't think a manual should encourage it.
