### ISSUE TITLE
Pear channel problem

### ISSUE THREAD

**Issue by Vitexus** [sebastianbergmann/phpunit-documentation#174]
If i try install as in documentation page http://phpunit.de/manual/current/en/skeleton-generator.html

root@HuP:~# pear install phpunit/PHPUnit_SkeletonGenerator
Attempting to discover channel "phpunit"...
Attempting fallback to https instead of http on channel "phpunit"...
unknown channel "phpunit" in "phpunit/PHPUnit_SkeletonGenerator"
invalid package name/package file "phpunit/PHPUnit_SkeletonGenerator"
install failed

But next command install all as well:
 pear install pear.phpunit.de/PHPUnit_SkeletonGenerator

**Comment by guywithnose** [comment]
I get this same issue even as root

```bash
[root@7d99b7753351 code]# pear install phpunit/PHPUnit_SkeletonGenerator
Attempting to discover channel "phpunit"...
Attempting fallback to https instead of http on channel "phpunit"...
unknown channel "phpunit" in "phpunit/PHPUnit_SkeletonGenerator"
invalid package name/package file "phpunit/PHPUnit_SkeletonGenerator"
install failed

**Comment by henriquemoody** [comment]
@guywithnose, the PEAR channel is no longer available: https://github.com/sebastianbergmann/phpunit/wiki/End-of-Life-for-PEAR-Installation-Method

**Comment by lucas-marciano** [comment]
http://stackoverflow.com/questions/12318446/pear-package-install-fails
