### ISSUE TITLE
Converting from PEAR  to Composer PHPUnit installation

### ISSUE THREAD

**Issue by Archanciel** [sebastianbergmann/phpunit-documentation#201]
Hi,

I did follow the advice displayed when running PHPUnit from the command line in a Windows 8.1 dos window

You have installed PHPUnit via PEAR. This installation method is no longer
supported and http://pear.phpunit.de/ will be shut down no later than
December, 31 2014.

and installed PHPUnit using Composer. I chosed a global (system wide) installation.

But now, my unit tests which were running ok in Eclipse using the Makegood plugin no longer run, Makegood sayis "PHPUnit_Framework_TestCase  class is not available". I don't have a clue on what was performed by the Composer installation of PHPUnit. Can you please provide information in order to facilitate solving this problem ?

Additiobally, when I run my unit tests from the command line, I still get 

You have installed PHPUnit via PEAR. This installation method is no longer
supported and http://pear.phpunit.de/ will be shut down no later than
December, 31 2014.

Thanks for improving the doc !
Jean-Pierre

**Comment by aseemaneja** [comment]
@Archanciel : Hi, Can you please help to convert from PEAR to composer PHPUnit Installation..
I'm unable to do !!
