### ISSUE TITLE
Traduzir citações

### ISSUE THREAD

**Issue by Gleidson2012** [sebastianbergmann/phpunit-documentation#294]
Boa noite!

Estou com dúvida sobre traduzir citações. Devemos ou não traduzi-las?

e.g.: <blockquote>
    <attribution>Martin Fowler</attribution>
    <para>
      Whenever you are tempted to type something into a
      <literal>print</literal> statement or a debugger expression, write it
      as a test instead.
    </para>
  </blockquote>

**Comment by henriquemoody** [comment]
Acredito que seja melhor traduzir ao invés de manter o idioma original visto que o objetivo da tradução do manual é justamente as pessoas que não conseguem ler no idioma original.

**Comment by Gleidson2012** [comment]
Entendi @henriquemoody.

Combinado.
