### ISSUE TITLE
Tradução para "Change Risk Anti-Patterns"?

### ISSUE THREAD

**Issue by Gleidson2012** [sebastianbergmann/phpunit-documentation#296]
Alguém tem alguma sugestão para a tradução do termo técnico "Change Risk Anti-Patterns"?
A que tenho no momento é Anti-Padrões de Mudança Arriscada.

@henriquemoody ?

**Comment by henriquemoody** [comment]
Complicado.

Provavelmente eu não traduziria _Anti-Patterns_.

Eu deixaria assim: _Anti-Patterns de Mudança de Risco_, mas não estou muito confortável com essa tradução ainda.

**Comment by Gleidson2012** [comment]
Entendi @henriquemoody.
Vou usar sua sugestão.
