### ISSUE TITLE
PHPUnit 4.7 and up does not consider unannotated tests as @small anymore

### ISSUE THREAD

**Issue by SvenRtbg** [sebastianbergmann/phpunit-documentation#311]
Per [Changelog of 4.7][changelog] release: 
Tests not annotated with @small, @medium, or @large are no longer treated as being annotated with @small

This is still [mentioned in the docs][docs]:
By default, all tests are considered to be small if they are not marked as @medium or @large.

[changelog]: <https://github.com/sebastianbergmann/phpunit/blob/14f174e5423cdcf9bf0a6f468b093b86959701ca/ChangeLog-4.7.md#L34>
[docs]: <https://github.com/sebastianbergmann/phpunit-documentation/blob/master/src/4.7/en/annotations.xml#L775-L783>

**Comment by ztec** [comment]
Linked to https://github.com/sebastianbergmann/phpunit/issues/2084
