### ISSUE TITLE
Include a CONTRIBUTING.md file

### ISSUE THREAD

**Issue by fireproofsocks** [sebastianbergmann/phpunit-documentation#328]
Contributing is more difficult than it needs to be.  It would be helpful to include a CONTRIBUTING.md file to outline what is required to contribute changes to the docs.  
1. It would also be helpful to give contributors a lay of the land to explain which files should be edited.  Are we supposed to update files in the src directory?  XML is not what users are probably expecting.  
2. Also, you should clarify here which folder to use when submitting edits.  If version 5.2/xx/ does not contain the file I wish to update, does the build process fall back to the latest version it can find?  I assume that's the case, but assumptions should be clarified.
3. Should we fork the repo?  Is there a branching structure or tagging convention you follow?

**Comment by nelson6e65** [comment]
:+1:

**Comment by sebastianbergmann** [comment]
Instead of the documenting the way it currently works I'd rather change the way it currently works to make it easier to contribute

* Replace DocBook/XML and XSLT with Markdown
* Only have one edition of the documentation instead of one per version
* ...

**Comment by fireproofsocks** [comment]
See https://github.com/sebastianbergmann/phpunit-documentation/pull/329

**Comment by sebastianbergmann** [comment]
Closing because of the reasons given in https://github.com/sebastianbergmann/phpunit-documentation/issues/328#issuecomment-149796959. The new process etc. is covered in #471.
