### ISSUE TITLE
XML <file> Tag Should Be On A Single Line

### ISSUE THREAD

**Issue by quantumpacket** [sebastianbergmann/phpunit-documentation#349]
Spent a bit of time trying to find out why PHPunit was not finding my test file, and it turns out it was due to the whitespace present from having the `<file>` tag on multiple lines. Putting it into a single line and the tests were found. I could not find such a requirement in the docs. It should either be put as a gotcha, or the value should be trimmed when it is being fetched. The multi-line format was not intentional and was done automatically by my IDE.

Finds File:
```xml
<file>./tests/MoneyTest.php</file>
```
Can't Find File:
```xml
<file>
    ./tests/MoneyTest.php
</file>
```
When using multi-line it provides no error message and just says "No tests executed!".

**Comment by sebastianbergmann** [comment]
This seems to be an issue in PHPUnit itself, not in its documentation. Please open a ticket for PHPUnit, thanks.

**Comment by quantumpacket** [comment]
Apologies, I assumed if it was a bug as trivial as this it would have been found years ago. So thought it was just a documentation issue. I'll open a ticket later today. Thanks for the speedy response!
