### ISSUE TITLE
Selenium configuration in phpunit.xml

### ISSUE THREAD

**Issue by webimpress** [sebastianbergmann/phpunit-documentation#372]
https://phpunit.de/manual/current/en/appendixes.configuration.html

Section `Configuring Browsers for Selenium RC` is wrong.

From Release notes 5.0.0:
> * The PHPUnit_Selenium component can no longer be configured using the `<selenium/browser>` element of PHPUnit's configuration file

**Comment by sebastianbergmann** [comment]
Closed via 6692d25cd27cc07034afba4df25bd14c0dce02c7.
