### ISSUE TITLE
Selenium2 PHPunit open Tab automatically

### ISSUE THREAD

**Issue by kathK** [sebastianbergmann/phpunit-documentation#373]
Hello!

I  am new and have an intressting problem.
I test C&P with Selenium Webdriver and PHPUnit. 
I open a new project, make my tests using the Keys Class and after the test I want delete the project. In my case, I have to click on a link to go on other page for delete, but the server dont chance the page, it opens a new tab in the background. And I dont know why.

Has someone an idea?

Bye bye Kathrin

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.
