### ISSUE TITLE
 Cannot open file 

### ISSUE THREAD

**Issue by lingeors** [sebastianbergmann/phpunit-documentation#381]
in Chapter 3 it tell us to run the command "phpunit ArrayTest" to run the actuator,
then I get the error  `Cannot open file "TryTest.php"` , after google for a long time, nothing get.
unexpectedly, i try to add `.php`, then it work. 
*therefore, maybe it will be better if the chapter 3 could make some explanation on it. *
> phpunit 5.5.0, windows 10 64bits, php 5.6
Thanks for the feedback

**Comment by sebastianbergmann** [comment]
Sorry, but I have no clue what you are trying to report. `TryTest` does not occur anywhere in the documentation.
