### ISSUE TITLE
How to configure phpunit.xml to output coverage-html?

### ISSUE THREAD

**Issue by trangit2** [sebastianbergmann/phpunit-documentation#401]
I attach my configuration for coverage-html phpunit testing.
I can not figure why it has not output coverage report yet.
Anyone show me why? Thanks
 [lt]phpunit bootstrap="./Bootstrap.php" colors="true"[gt]
	[lt]testsuite name="Unit Testing"[gt]
		[lt]directory[gt]./[lt]/directory[gt]
	[lt]/testsuite[gt]
	[lt]filter[gt]
		[lt]whitelist[gt]
			[lt]directory suffix=".php"[gt]./[lt]/directory[gt]
			[lt]file[gt]./[lt]/file[gt]
			[lt]exclude[gt]
				[lt]directory suffix=".phtml"[gt]../application/[lt]/directory[gt]
			[lt]/exclude[gt]
		[lt]/whitelist[gt]
	[lt]/filter[gt]

	[lt]logging[gt]
		[lt]log type="coverage-html" target="/log/report/" charset="UTF-8"
			yui="true" highlight="true" lowUpperBound="50" highLowerBound="80" /[gt]
	[lt]/logging[gt]
[lt]/phpunit[gt]

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.
