### ISSUE TITLE
How can I set a full HTTP_HOST in phpunit.xml or in the createClient()

### ISSUE THREAD

**Issue by sergmoro1** [sebastianbergmann/phpunit-documentation#404]
Hi!
I start my app locally by http://sm1/app/web/app_dev.php (symfony3)

In a test file
$client = static::createClient([], ['HTTP_HOST' => 'sm1/app/web/app_dev.php']);

But after
$crawler = $client->request('GET', '/good/');

In a log file I've got
request.INFO: Matched route "{route}". {"route":"good_index","route_parameters":{"_controller":"AppBundle\\Controller\\GoodController::indexAction","_route":"good_index"},"request_uri":"http://sm1/good/","method":"GET"} []

How can I set a full path?

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.

**Comment by sergmoro1** [comment]
"Please open a ticket on GitHub to suggest improvements"

Please, place some links in a Doc where users can get help.

**Comment by sergmoro1** [comment]
http://stackoverflow.com/questions/41288377/how-can-be-fixed-an-error-of-phpunit-when-other-local-address-then-http-loc/41300115#4130011
