### ISSUE TITLE
Unsafe script request blocked

### ISSUE THREAD

**Issue by Krinkle** [sebastianbergmann/phpunit-documentation#407]
<img width="1436" alt="screen shot 2017-01-10 at 15 41 15" src="https://cloud.githubusercontent.com/assets/156867/21829514/41ad3ee0-d74b-11e6-80b2-8c9ccd7945c3.png">

> [Error] Mixed Content: The page at 'https://phpunit.de/manual/4.8/en/test-doubles.html#test-doubles.stubs' was loaded over HTTPS, but requested an insecure resource 'http://lore.circulate.com/rysc?fid=lrttum'. **This request has been blocked**; the content **must** be served over HTTPS.

> [Warning] Mixed Content: The page at 'https://phpunit.de/manual/4.8/en/test-doubles.html#test-doubles.stubs' was loaded over HTTPS, but requested an **insecure image** 'http://p.adsymptotic.com/d/px?..'. This content **should** also be served over HTTPS.

**Comment by sebastianbergmann** [comment]
Should be fixed by 5198537f82f4a31c4921da14f03765bfa9624669.
