### ISSUE TITLE
Missing documentation for getActualOutput

### ISSUE THREAD

**Issue by schnittstabil** [sebastianbergmann/phpunit-documentation#409]
[`PHPUnit_Framework_TestCase::getActualOutput()`](https://github.com/sebastianbergmann/phpunit/blob/c37b6e72490c22099660e5355c47eca45daaa201/src/Framework/TestCase.php#L438-L450) seems to be by far the most valuable method for sophisticated output testing; unfortunately, it is not mentioned at [Testing Output](https://phpunit.de/manual/current/en/writing-tests-for-phpunit.html#writing-tests-for-phpunit.output).

– I'm willing to create a PR, but this method is available since 3.6.0 and I don't know how you deal with that: Should I _manually_ (or by means of `ed`/`sed`) modify every single `[3.6…6.0]/*/writing-tests-for-phpunit.xml`?

**Comment by sebastianbergmann** [comment]
Not every public method needs to be documented, sorry.

**Comment by sebastianbergmann** [comment]
Sure, feel free to send a pull request. Adding this to the manual for 4.8, 5.7, and 6.0 is enough.
