### ISSUE TITLE
Serious error in documentation in portuguese

### ISSUE THREAD

**Issue by geekcom** [sebastianbergmann/phpunit-documentation#411]
From their manual in Portuguese:
https://phpunit.de/manual/current/pt_br/installation.html#installation.requirements:

> Capítulo 1. Instalando PHPUnit
Requerimentos

> PHPUnit 5.7 requer PHP 5.3.3;

In neither translation of the manual says the same way, see the original version: 
https://phpunit.de/manual/current/en/installation.html#installation.requirements
> PHPUnit 5.7 requires PHP 5.6; 

This can cause many problems in the installation, i hope it will be solved soon.

Thanks.

**Comment by sebastianbergmann** [comment]
I do not think that the Portuguese translation is maintained.

**Comment by geekcom** [comment]
It's ok @sebastianbergmann,  #412  that's fix
