### ISSUE TITLE
issue with  "phpunit/php-invoker": "*" , under linux 

### ISSUE THREAD

**Issue by GMA-216** [sebastianbergmann/phpunit-documentation#414]
Hi,

during installation of PHPUnit, on [this page](https://phpunit.de/manual/current/en/installation.html#installation.phar.verification) there is 2 "Optional packages", could be installed, of through the author: 
First, I tried as it's mentioned: 

**composer global require "phpunit/php-invoker": "*"**

I got this error:  

> [InvalidArgumentException]                                                                         
>   Could not find package * at any version for your minimum-stability (stable). Check the package sp  
>   elling or your minimum-stability
                                                                   
The solution  :  
 **composer global require "phpunit/php-invoker": ">=1"**           

I got this : 

> Changed current directory to /home/amine/.composer
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
>   - Installing phpunit/php-invoker (1.1.4)
>     Downloading: 100%         
> 
> Writing lock file
> Generating autoload files

have a good day :)

**Comment by sebastianbergmann** [comment]
The documentation says `composer require --dev phpunit/php-invoker`.
