### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by damienflament** [sebastianbergmann/phpunit-documentation#417]
Hi!

Do you plan to publish the PHPUnit API documentation alongside the current descriptive/narrative documentation ?

I like the actual documentation. But, as the source code is documented (with examples), an API documentation allow a better understanding of some _advanced_ usage.

As I didn't found any API documentation, I build it using Sami for [PHPUnit ](https://github.com/damienflament/phpunit-api-docs)and [PHPUnit Mock Objects](https://github.com/damienflament/phpunit-mock-objects-api-docs).

**Comment by sebastianbergmann** [comment]
API documentation is available at `https://api.phpunit.de/`.

**Comment by damienflament** [comment]
Nice ! I didn't find any link to the API documentation within the documentation available on the main website. Even via a simple Google search.
