### ISSUE TITLE
Cannot install Skeleton Generator with pear or composer. Gone?

### ISSUE THREAD

**Issue by sfsccn** [sebastianbergmann/phpunit-documentation#457]
Hi, the page https://phpunit.de/manual/3.7/en/skeleton-generator.html has:

`pear install phpunit/PHPUnit_SkeletonGenerator`

However, pear says: unknown channel "phpunit" (PHP 7.1.8, PEAR 1.10.5). This page may be relevant: https://github.com/sebastianbergmann/phpunit/wiki/End-of-Life-for-PEAR-Installation-Method.

Furthermore, adding the following to my composer.json file:

```
    "require-dev": {
        "phpunit/phpunit": "6.2.4",
        "phpunit/phpunit-skeleton-generator": "*"        
    },
```

results in conflicts:

* phpunit/phpunit 6.2.4 requires sebastian/version ^2.0
* phpunit/phpunit-skeleton-generator 2.0.0 requires sebastian/version ~1.0

The [phpunit-skeleton-generator packagist page](https://packagist.org/packages/phpunit/phpunit-skeleton-generator) says:

> This package is abandoned and no longer maintained. No replacement package was suggested.

Is there any point in attempting to use this package or is it pretty much gone?

**Comment by sebastianbergmann** [comment]
PHPUnit 3.7 has not been supported in years and the skeleton generator has been abandoned long ago.

**Comment by sfsccn** [comment]
Ah, wrong manual, sorry. Must have landed on it via google.
