### ISSUE TITLE
Command line doesn't exist even though composer installation succeeded.

### ISSUE THREAD

**Issue by rkevinburton** [sebastianbergmann/phpunit-documentation#460]
I type 'composer require --dev phpunit/phpunit ^6.3'. The command seemed to install without error but when I issue 'phpunit --version' on Windows 10 I get ''phpunit' is not recognized as an internal or external command, operable program or batch file.' Ideas?

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.
